cp data/fileList_QCDflat_710pre8_posHCAL_jetCoreTrack_clusterSplit_splitMergedNeutrals.txt data/fileList_QCDflat_710pre8_posHCAL_jetCoreTrack_clusterSplit.txt
cp data/fileList_WW2000_710pre8_posHCAL_jetCoreTrack_clusterSplit_splitMergedNeutrals.txt data/fileList_WW2000_710pre8_posHCAL_jetCoreTrack_clusterSplit.txt
cp data/fileList_WW3000_710pre8_posHCAL_jetCoreTrack_clusterSplit_splitMergedNeutrals.txt data/fileList_WW3000_710pre8_posHCAL_jetCoreTrack_clusterSplit.txt
cp data/fileList_WW4000_710pre8_posHCAL_jetCoreTrack_clusterSplit_splitMergedNeutrals.txt data/fileList_WW4000_710pre8_posHCAL_jetCoreTrack_clusterSplit.txt
cp data/fileList_qW5000_710pre8_posHCAL_jetCoreTrack_clusterSplit_splitMergedNeutrals.txt data/fileList_qW5000_710pre8_posHCAL_jetCoreTrack_clusterSplit.txt
cp data/fileList_qW7000_710pre8_posHCAL_jetCoreTrack_clusterSplit_splitMergedNeutrals.txt data/fileList_qW7000_710pre8_posHCAL_jetCoreTrack_clusterSplit.txt

cp data/fileList_QCDflat_710pre8_posHCAL_jetCoreTrack_clusterSplit_splitMergedNeutrals.txt data/fileList_QCDflat_710pre8_posHCAL_splitMergedNeutrals.txt
cp data/fileList_WW2000_710pre8_posHCAL_jetCoreTrack_clusterSplit_splitMergedNeutrals.txt data/fileList_WW2000_710pre8_posHCAL_splitMergedNeutrals.txt
cp data/fileList_WW3000_710pre8_posHCAL_jetCoreTrack_clusterSplit_splitMergedNeutrals.txt data/fileList_WW3000_710pre8_posHCAL_splitMergedNeutrals.txt
cp data/fileList_WW4000_710pre8_posHCAL_jetCoreTrack_clusterSplit_splitMergedNeutrals.txt data/fileList_WW4000_710pre8_posHCAL_splitMergedNeutrals.txt
cp data/fileList_qW5000_710pre8_posHCAL_jetCoreTrack_clusterSplit_splitMergedNeutrals.txt data/fileList_qW5000_710pre8_posHCAL_splitMergedNeutrals.txt
cp data/fileList_qW7000_710pre8_posHCAL_jetCoreTrack_clusterSplit_splitMergedNeutrals.txt data/fileList_qW7000_710pre8_posHCAL_splitMergedNeutrals.txt

cp data/fileList_QCDflat_710pre8_posHCAL_jetCoreTrack_clusterSplit_splitMergedNeutrals.txt data/fileList_QCDflat_710pre8_jetCoreTrack_clusterSplit_splitMergedNeutrals.txt
cp data/fileList_WW2000_710pre8_posHCAL_jetCoreTrack_clusterSplit_splitMergedNeutrals.txt data/fileList_WW2000_710pre8_jetCoreTrack_clusterSplit_splitMergedNeutrals.txt
cp data/fileList_WW3000_710pre8_posHCAL_jetCoreTrack_clusterSplit_splitMergedNeutrals.txt data/fileList_WW3000_710pre8_jetCoreTrack_clusterSplit_splitMergedNeutrals.txt
cp data/fileList_WW4000_710pre8_posHCAL_jetCoreTrack_clusterSplit_splitMergedNeutrals.txt data/fileList_WW4000_710pre8_jetCoreTrack_clusterSplit_splitMergedNeutrals.txt
cp data/fileList_qW5000_710pre8_posHCAL_jetCoreTrack_clusterSplit_splitMergedNeutrals.txt data/fileList_qW5000_710pre8_jetCoreTrack_clusterSplit_splitMergedNeutrals.txt
cp data/fileList_qW7000_710pre8_posHCAL_jetCoreTrack_clusterSplit_splitMergedNeutrals.txt data/fileList_qW7000_710pre8_jetCoreTrack_clusterSplit_splitMergedNeutrals.txt

