substructure_pas data/fileList_QCD30.txt substructure_pas_QCD30.root > substructure_pas_QCD30.log &
substructure_pas data/fileList_QCD170.txt substructure_pas_QCD170.root > substructure_pas_QCD170.log &
substructure_pas data/fileList_QCD1000.txt substructure_pas_QCD1000.root > substructure_pas_QCD1000.log &
substructure_pas data/fileList_WW3000.txt substructure_pas_WW3000.root > substructure_pas_WW3000.log &
substructure_pas data/fileList_QCD30_posCAL.txt substructure_pas_QCD30_posCAL.root > substructure_pas_QCD30_posCAL.log &
substructure_pas data/fileList_QCD170_posCAL.txt substructure_pas_QCD170_posCAL.root > substructure_pas_QCD170_posCAL.log &
substructure_pas data/fileList_QCD1000_posCAL.txt substructure_pas_QCD1000_posCAL.root > substructure_pas_QCD1000_posCAL.log &
substructure_pas data/fileList_WW3000_posCAL.txt substructure_pas_WW3000_posCAL.root > substructure_pas_WW3000_posCAL.log &
substructure_pas data/fileList_QCD30_fixHCAL.txt substructure_pas_QCD30_fixHCAL.root > substructure_pas_QCD30_fixHCAL.log &
substructure_pas data/fileList_QCD170_fixHCAL.txt substructure_pas_QCD170_fixHCAL.root > substructure_pas_QCD170_fixHCAL.log &
substructure_pas data/fileList_QCD1000_fixHCAL.txt substructure_pas_QCD1000_fixHCAL.root > substructure_pas_QCD1000_fixHCAL.log &
substructure_pas data/fileList_WW3000_fixHCAL.txt substructure_pas_WW3000_fixHCAL.root > substructure_pas_WW3000_fixHCAL.log &
substructure_pas data/fileList_QCD30_fixTRACK.txt substructure_pas_QCD30_fixTRACK.root > substructure_pas_QCD30_fixTRACK.log &
substructure_pas data/fileList_QCD170_fixTRACK.txt substructure_pas_QCD170_fixTRACK.root > substructure_pas_QCD170_fixTRACK.log &
substructure_pas data/fileList_QCD1000_fixTRACK.txt substructure_pas_QCD1000_fixTRACK.root > substructure_pas_QCD1000_fixTRACK.log &
substructure_pas data/fileList_WW3000_fixTRACK.txt substructure_pas_WW3000_fixTRACK.root > substructure_pas_WW3000_fixTRACK.log &
substructure_pas data/fileList_QCD30_fixTRACK_noHCAL.txt substructure_pas_QCD30_fixTRACK_noHCAL.root > substructure_pas_QCD30_fixTRACK_noHCAL.log &
substructure_pas data/fileList_QCD170_fixTRACK_noHCAL.txt substructure_pas_QCD170_fixTRACK_noHCAL.root > substructure_pas_QCD170_fixTRACK_noHCAL.log &
substructure_pas data/fileList_QCD1000_fixTRACK_noHCAL.txt substructure_pas_QCD1000_fixTRACK_noHCAL.root > substructure_pas_QCD1000_fixTRACK_noHCAL.log &
substructure_pas data/fileList_WW3000_fixTRACK_noHCAL.txt substructure_pas_WW3000_fixTRACK_noHCAL.root > substructure_pas_WW3000_fixTRACK_noHCAL.log &
substructure_pas data/fileList_QCD30_posHCAL_fixTRACK_showerSigma8.txt substructure_pas_QCD30_posHCAL_fixTRACK_showerSigma8.root > substructure_pas_QCD30_posHCAL_fixTRACK_showerSigma8.log &
substructure_pas data/fileList_QCD170_posHCAL_fixTRACK_showerSigma8.txt substructure_pas_QCD170_posHCAL_fixTRACK_showerSigma8.root > substructure_pas_QCD170_posHCAL_fixTRACK_showerSigma8.log &
substructure_pas data/fileList_QCD1000_posHCAL_fixTRACK_showerSigma8.txt substructure_pas_QCD1000_posHCAL_fixTRACK_showerSigma8.root > substructure_pas_QCD1000_posHCAL_fixTRACK_showerSigma8.log &
substructure_pas data/fileList_WW3000_posHCAL_fixTRACK_showerSigma8.txt substructure_pas_WW3000_posHCAL_fixTRACK_showerSigma8.root > substructure_pas_WW3000_posHCAL_fixTRACK_showerSigma8.log &

substructure_pas data/fileList_QCD30_posHCAL_fixTRACK.txt substructure_pas_QCD30_posHCAL_fixTRACK.root > substructure_pas_QCD30_posHCAL_fixTRACK.log &
substructure_pas data/fileList_QCD170_posHCAL_fixTRACK.txt substructure_pas_QCD170_posHCAL_fixTRACK.root > substructure_pas_QCD170_posHCAL_fixTRACK.log &
substructure_pas data/fileList_QCD1000_posHCAL_fixTRACK.txt substructure_pas_QCD1000_posHCAL_fixTRACK.root > substructure_pas_QCD1000_posHCAL_fixTRACK.log &
substructure_pas data/fileList_QCD1800_posHCAL_fixTRACK.txt substructure_pas_QCD1800_posHCAL_fixTRACK.root > substructure_pas_QCD1800_posHCAL_fixTRACK.log &
substructure_pas data/fileList_WW3000_posHCAL_fixTRACK.txt substructure_pas_WW3000_posHCAL_fixTRACK.root > substructure_pas_WW3000_posHCAL_fixTRACK.log &
substructure_pas data/fileList_WW2000_posHCAL_fixTRACK.txt substructure_pas_WW2000_posHCAL_fixTRACK.root > substructure_pas_WW2000_posHCAL_fixTRACK.log &
substructure_pas data/fileList_WW4000_posHCAL_fixTRACK.txt substructure_pas_WW4000_posHCAL_fixTRACK.root > substructure_pas_WW4000_posHCAL_fixTRACK.log &
substructure_pas data/fileList_qW5000_posHCAL_fixTRACK.txt substructure_pas_qW5000_posHCAL_fixTRACK.root > substructure_pas_qW5000_posHCAL_fixTRACK.log &
substructure_pas data/fileList_qW7000_posHCAL_fixTRACK.txt substructure_pas_qW7000_posHCAL_fixTRACK.root > substructure_pas_qW7000_posHCAL_fixTRACK.log &

substructure_pas data/fileList_QCD1000_posHCAL_fixTRACK_splitPFecal2.txt substructure_pas_QCD1000_posHCAL_fixTRACK_splitPFecal2.root > substructure_pas_QCD1000_posHCAL_fixTRACK_splitPFecal2.log &
substructure_pas data/fileList_WW3000_posHCAL_fixTRACK_splitPFecal2.txt substructure_pas_WW3000_posHCAL_fixTRACK_splitPFecal2.root > substructure_pas_WW3000_posHCAL_fixTRACK_splitPFecal2.log &
substructure_pas data/fileList_QCD1000_posHCAL_fixTRACK_splitPFecal3.txt substructure_pas_QCD1000_posHCAL_fixTRACK_splitPFecal3.root > substructure_pas_QCD1000_posHCAL_fixTRACK_splitPFecal3.log &
substructure_pas data/fileList_WW3000_posHCAL_fixTRACK_splitPFecal3.txt substructure_pas_WW3000_posHCAL_fixTRACK_splitPFecal3.root > substructure_pas_WW3000_posHCAL_fixTRACK_splitPFecal3.log &
substructure_pas data/fileList_WW4000_posHCAL_fixTRACK_splitPFecal3.txt substructure_pas_WW4000_posHCAL_fixTRACK_splitPFecal3.root > substructure_pas_WW4000_posHCAL_fixTRACK_splitPFecal3.log &

substructure_pas data/fileList_QCD30_posHCAL_fixTRACK_splitPFecal.txt substructure_pas_QCD30_posHCAL_fixTRACK_splitPFecal.root > substructure_pas_QCD30_posHCAL_fixTRACK_splitPFecal.log &
substructure_pas data/fileList_QCD170_posHCAL_fixTRACK_splitPFecal.txt substructure_pas_QCD170_posHCAL_fixTRACK_splitPFecal.root > substructure_pas_QCD170_posHCAL_fixTRACK_splitPFecal.log &
substructure_pas data/fileList_QCD1000_posHCAL_fixTRACK_splitPFecal.txt substructure_pas_QCD1000_posHCAL_fixTRACK_splitPFecal.root > substructure_pas_QCD1000_posHCAL_fixTRACK_splitPFecal.log &
substructure_pas data/fileList_QCD1800_posHCAL_fixTRACK_splitPFecal.txt substructure_pas_QCD1800_posHCAL_fixTRACK_splitPFecal.root > substructure_pas_QCD1800_posHCAL_fixTRACK_splitPFecal.log &
substructure_pas data/fileList_WW3000_posHCAL_fixTRACK_splitPFecal.txt substructure_pas_WW3000_posHCAL_fixTRACK_splitPFecal.root > substructure_pas_WW3000_posHCAL_fixTRACK_splitPFecal.log &
substructure_pas data/fileList_WW2000_posHCAL_fixTRACK_splitPFecal.txt substructure_pas_WW2000_posHCAL_fixTRACK_splitPFecal.root > substructure_pas_WW2000_posHCAL_fixTRACK_splitPFecal.log &
substructure_pas data/fileList_WW4000_posHCAL_fixTRACK_splitPFecal.txt substructure_pas_WW4000_posHCAL_fixTRACK_splitPFecal.root > substructure_pas_WW4000_posHCAL_fixTRACK_splitPFecal.log &
substructure_pas data/fileList_qW3000_posHCAL_fixTRACK_splitPFecal.txt substructure_pas_qW3000_posHCAL_fixTRACK_splitPFecal.root > substructure_pas_qW3000_posHCAL_fixTRACK_splitPFecal.log &
substructure_pas data/fileList_qW5000_posHCAL_fixTRACK_splitPFecal.txt substructure_pas_qW5000_posHCAL_fixTRACK_splitPFecal.root > substructure_pas_qW5000_posHCAL_fixTRACK_splitPFecal.log &
substructure_pas data/fileList_qW7000_posHCAL_fixTRACK_splitPFecal.txt substructure_pas_qW7000_posHCAL_fixTRACK_splitPFecal.root > substructure_pas_qW7000_posHCAL_fixTRACK_splitPFecal.log &

substructure_pas data/fileList_WW3000_posHCAL_noSplitting.txt substructure_pas_WW3000_posHCAL_noSplitting.root > substructure_pas_WW3000_posHCAL_noSplitting.log &
substructure_pas data/fileList_WW3000_posHCAL_splitting.txt substructure_pas_WW3000_posHCAL_splitting.root > substructure_pas_WW3000_posHCAL_splitting.log &
substructure_pas data/fileList_WW4000_posHCAL_noSplitting.txt substructure_pas_WW4000_posHCAL_noSplitting.root > substructure_pas_WW4000_posHCAL_noSplitting.log &
substructure_pas data/fileList_WW4000_posHCAL_splitting.txt substructure_pas_WW4000_posHCAL_splitting.root > substructure_pas_WW4000_posHCAL_splitting.log &

substructure_pas data/fileList_QCD30_posHCAL_PU.txt substructure_pas_QCD30_posHCAL_PU.root > substructure_pas_QCD30_posHCAL_PU.log &
substructure_pas data/fileList_QCD170_posHCAL_PU.txt substructure_pas_QCD170_posHCAL_PU.root > substructure_pas_QCD170_posHCAL_PU.log &
substructure_pas data/fileList_QCD1000_posHCAL_PU.txt substructure_pas_QCD1000_posHCAL_PU.root > substructure_pas_QCD1000_posHCAL_PU.log &
substructure_pas data/fileList_QCD1800_posHCAL_PU.txt substructure_pas_QCD1800_posHCAL_PU.root > substructure_pas_QCD1800_posHCAL_PU.log &
substructure_pas data/fileList_WW3000_posHCAL_PU.txt substructure_pas_WW3000_posHCAL_PU.root > substructure_pas_WW3000_posHCAL_PU.log &
substructure_pas data/fileList_WW2000_posHCAL_PU.txt substructure_pas_WW2000_posHCAL_PU.root > substructure_pas_WW2000_posHCAL_PU.log &
substructure_pas data/fileList_WW4000_posHCAL_PU.txt substructure_pas_WW4000_posHCAL_PU.root > substructure_pas_WW4000_posHCAL_PU.log &
substructure_pas data/fileList_qW5000_posHCAL_PU.txt substructure_pas_qW5000_posHCAL_PU.root > substructure_pas_qW5000_posHCAL_PU.log &
substructure_pas data/fileList_qW7000_posHCAL_PU.txt substructure_pas_qW7000_posHCAL_PU.root > substructure_pas_qW7000_posHCAL_PU.log &

substructure_pas data/fileList_QCD30_posHCAL.txt substructure_pas_QCD30_posHCAL.root > substructure_pas_QCD30_posHCAL.log &
substructure_pas data/fileList_QCD170_posHCAL.txt substructure_pas_QCD170_posHCAL.root > substructure_pas_QCD170_posHCAL.log &
substructure_pas data/fileList_QCD1000_posHCAL.txt substructure_pas_QCD1000_posHCAL.root > substructure_pas_QCD1000_posHCAL.log &
substructure_pas data/fileList_QCD1800_posHCAL.txt substructure_pas_QCD1800_posHCAL.root > substructure_pas_QCD1800_posHCAL.log &
substructure_pas data/fileList_WW3000_posHCAL.txt substructure_pas_WW3000_posHCAL.root > substructure_pas_WW3000_posHCAL.log &
substructure_pas data/fileList_WW2000_posHCAL.txt substructure_pas_WW2000_posHCAL.root > substructure_pas_WW2000_posHCAL.log &
substructure_pas data/fileList_WW4000_posHCAL.txt substructure_pas_WW4000_posHCAL.root > substructure_pas_WW4000_posHCAL.log &
substructure_pas data/fileList_qW5000_posHCAL.txt substructure_pas_qW5000_posHCAL.root > substructure_pas_qW5000_posHCAL.log &
substructure_pas data/fileList_qW7000_posHCAL.txt substructure_pas_qW7000_posHCAL.root > substructure_pas_qW7000_posHCAL.log &

substructure_pas data/fileList_QCD30_posHCAL_fixTRACK_splitPFecal_new.txt substructure_pas_QCD30_posHCAL_fixTRACK_splitPFecal_new.root > substructure_pas_QCD30_posHCAL_fixTRACK_splitPFecal_new.log &
substructure_pas data/fileList_QCD170_posHCAL_fixTRACK_splitPFecal_new.txt substructure_pas_QCD170_posHCAL_fixTRACK_splitPFecal_new.root > substructure_pas_QCD170_posHCAL_fixTRACK_splitPFecal_new.log &
substructure_pas data/fileList_QCD1000_posHCAL_fixTRACK_splitPFecal_new.txt substructure_pas_QCD1000_posHCAL_fixTRACK_splitPFecal_new.root > substructure_pas_QCD1000_posHCAL_fixTRACK_splitPFecal_new.log &
substructure_pas data/fileList_QCD1800_posHCAL_fixTRACK_splitPFecal_new.txt substructure_pas_QCD1800_posHCAL_fixTRACK_splitPFecal_new.root > substructure_pas_QCD1800_posHCAL_fixTRACK_splitPFecal_new.log &
substructure_pas data/fileList_WW3000_posHCAL_fixTRACK_splitPFecal_new.txt substructure_pas_WW3000_posHCAL_fixTRACK_splitPFecal_new.root > substructure_pas_WW3000_posHCAL_fixTRACK_splitPFecal_new.log &
substructure_pas data/fileList_WW2000_posHCAL_fixTRACK_splitPFecal_new.txt substructure_pas_WW2000_posHCAL_fixTRACK_splitPFecal_new.root > substructure_pas_WW2000_posHCAL_fixTRACK_splitPFecal_new.log &
substructure_pas data/fileList_WW4000_posHCAL_fixTRACK_splitPFecal_new.txt substructure_pas_WW4000_posHCAL_fixTRACK_splitPFecal_new.root > substructure_pas_WW4000_posHCAL_fixTRACK_splitPFecal_new.log &
substructure_pas data/fileList_qW3000_posHCAL_fixTRACK_splitPFecal_new.txt substructure_pas_qW3000_posHCAL_fixTRACK_splitPFecal_new.root > substructure_pas_qW3000_posHCAL_fixTRACK_splitPFecal_new.log &
substructure_pas data/fileList_qW5000_posHCAL_fixTRACK_splitPFecal_new.txt substructure_pas_qW5000_posHCAL_fixTRACK_splitPFecal_new.root > substructure_pas_qW5000_posHCAL_fixTRACK_splitPFecal_new.log &
substructure_pas data/fileList_qW7000_posHCAL_fixTRACK_splitPFecal_new.txt substructure_pas_qW7000_posHCAL_fixTRACK_splitPFecal_new.root > substructure_pas_qW7000_posHCAL_fixTRACK_splitPFecal_new.log &

